[#-- This custom link component can include an image. --]
[#-------------- INCLUDE AND ASSIGN PART --------------]

[#include "/mtk/templates/includes/init.ftl"]

[#-- Custom image macro for links only --]
[#-- Renders an image (asset) rendition --]
[#macro image image content imageClass="img-responsive" useOriginal=false]
    [#if image?has_content]
        [#-- Fallback text for alt text --]
        [#assign assetTitle=i18n['image.alt.unavailable']!]
        [#if image.asset?? && image.asset.title?has_content]
            [#assign assetTitle=image.asset.title]
        [/#if]

        [#-- Alt text and title --]
        [#assign imageAlt=content.altText!content.title!i18n['image.alt.prefix']+": "+assetTitle]
        [#assign imageTitle=content.title!content.altText!i18n['image.alt.prefix']+": "+assetTitle]

        [#assign imageLink=image.link /]
        [#-- For PNGs it might be useful to use render the original asset and therefore bypassing imaging --]
        [#if useOriginal]
            [#assign imageLink=image.asset.link /]
        [/#if]

        [#-- Render the image --]
    <img src="${imageLink}" alt="${imageAlt}" title="${imageTitle}" class="${imageClass}"/>
    [/#if]
[/#macro]

[#assign hasImage=false]
[#if content.image?exists && content.image?has_content]
    [#assign hasImage=true]
[/#if]

[#if content.linkType?has_content]
    [#assign divClass = "${content.linkType} ${divClass}"]
[/#if]

[#assign linkText = content.title!]

[#if content.linkType == "page"]
    [#assign target = cmsfn.contentByReference(content, "linkTypepage", "website")!]
    [#-- Ensure target node exists and it's not deleted --]
    [#if target?has_content && !cmsfn.asJCRNode(target).hasProperty("mgnl:deleted")]
        [#assign linkHref = cmsfn.link(target)!]
        [#if !(linkText?has_content)]
            [#assign linkText = target.title!target.name!]
        [/#if]
    [/#if]
[#else]
    [#assign linkHref = content.link!]
[/#if]

[#if content.linkType == "download"]
    [#assign assetId = content.linkTypedownload!]
    [#if assetId?has_content]
        [#assign asset = damfn.getAsset(assetId)!]
            [#if asset?has_content]
                [#assign linkHref = asset.link]
                [#assign extension = cmsfn.fileExtension(asset.fileName)]
                [#if !(linkText?has_content)]
                    [#assign linkText =  "${asset.title!asset.fileName!} <em>(" + extension?upper_case + ", " + cmsfn.readableFileSize(asset.fileSize) + ")</em>"]
                [/#if]
            [/#if]
    [/#if]
[/#if]

[#-- Show resolve error in edit mode for internal/download links --]
[#if content.linkType == "page" || content.linkType == "download"]
    [#if !(linkHref?has_content) && cmsfn.editMode]
        [#assign linkText = "${i18n['reference.resolveError']}"]
        [#assign divClass = "${divClass} note-for-editor"]
    [/#if]
[/#if]

[#if content.linkType == "external" && !linkHref?starts_with("#")]
    [#assign linkTarget = " target=\"_blank\""]
[/#if]

[#-------------- RENDERING  --------------]
[#if linkHref?exists || cmsfn.editMode]
<span class="${divClass!}"${divID}><a href="${linkHref}"${linkTarget!}>
    [#if hasImage]
        [#assign assetRendition=damfn.getRendition(content.image, "original")]
        [@image assetRendition content "list-image" true /]
    [#else]
        ${linkText}
    [/#if]
</a></span>
[/#if]
