[#function detectCookie cookieName]
    [#list ctx.request.cookies as cookie]
        [#if cookie.name == cookieName]
            [#return cookie.value]
        [/#if]
    [/#list]
    [#return ""]
[/#function]
