[#function detectCookie cookieName]
    [#if ctx?? && ctx.request?? && ctx.request?has_content]
        [#list ctx.request.cookies as cookie]
            [#if cookie.name == cookieName]
                [#return cookie.value]
            [/#if]
        [/#list]
    [/#if]
    [#return ""]
[/#function]
